### ISSUE TITLE
unable to find in chrome extension  when i search directly "netcat" in chrome store,

### ISSUE THREAD

**Issue by HackerGprat** [vapier/chrome-ext-netcat#1]
incidentally i found your chrome app during search result, because i was searching netcat online, 
after founding your cool netcat web apps, 
i tried to search again in webstore directly but there was no result of yours... why, only i can access it using the link , not using search bar why???

**Comment by vapier** [comment]
Chrome has deprecated Chrome Apps:
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

So if you're not using Chrome OS, you won't be able to find them via search in the Chrome Web Store anymore.  Nothing I can do about it.
